semi: false
singleQuote: true
tabWidth: 2
trailingComma: none
arrowParens: avoid
bracketSpacing: true
jsxBracketSameLine: false
jsxSingleQuote: false
printWidth: 160
useTabs: true
quoteProps: as-needed
